AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  PrivateMusicAlexaSkillLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: privateMusicAlexaSkill
      Runtime: java11
      Handler: f18a14c09s.integration.aws.PrivateMusicAlexaSkillRequestHandler::handleRequest
      CodeUri: ./target/lambda.jar
      MemorySize: 10240
      Timeout: 60
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill

  StringPartitionKeyStringSortKeyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-StringPartitionKeyStringSortKeyTable"
      BillingMode: PAY_PER_REQUEST
      TableClass: STANDARD_INFREQUENT_ACCESS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
#      ContributorInsightsSpecification:
#        ContributorInsightsSpecification
#      GlobalSecondaryIndexes:
#        - ContributorInsightsSpecification:
#            ContributorInsightsSpecification
#          IndexName: String
#          KeySchema:
#            - KeySchema
#          Projection:
#            Projection
#          ProvisionedThroughput:
#            ProvisionedThroughput
#      ImportSourceSpecification:
#        ImportSourceSpecification
#      KinesisStreamSpecification:
#        KinesisStreamSpecification
#      LocalSecondaryIndexes:
#        - IndexName: String
#          KeySchema:
#            - KeySchema
#          Projection:
#            Projection
#      ProvisionedThroughput:
#        ReadCapacityUnits: 1
#        WriteCapacityUnits: 1
#      SSESpecification:
#        SSESpecification
#      StreamSpecification:
#        StreamSpecification
#      Tags:
#        - Tag
#      TimeToLiveSpecification:
#        TimeToLiveSpecification

  StringPartitionKeyNumericSortKeyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-StringPartitionKeyNumericSortKeyTable"
      BillingMode: PAY_PER_REQUEST
      TableClass: STANDARD_INFREQUENT_ACCESS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: N
