AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::LanguageExtensions

Resources:
  PrivateMusicAlexaSkillLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: privateMusicAlexaSkill
      AutoPublishAlias: latest
      Runtime: java11
      Handler: f18a14c09s.integration.aws.PrivateMusicAlexaSkillRequestHandler::handleRequest
      CodeUri: ./target/lambda.jar
      MemorySize: 4096
      Timeout: 15
#      ProvisionedConcurrencyConfig:
#        ProvisionedConcurrentExecutions: 1
      SnapStart:
        ApplyOn: PublishedVersions
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
#        ScheduleBasedWarmer:
#          Type: ScheduleV2
#          Properties:
#            Description: !Sub "Keep ${AWS::StackName} Lambda function warmer."
#            ScheduleExpression: rate(5 minutes)
#            Input:
#              Fn::ToJsonString:
#                header:
#                  messageId: FakeMessageId123
#                  namespace: Alexa.Media.Search
#                  name: GetPlayableContent
#                  payloadVersion: 1.0
#                payload:
#                  requestContext:
#                    user:
#                      id: fake.Alexa.user.ID
#                    location:
#                      originatingLocale: en-US
#                      countryCode: US
#                  filters:
#                    explicitLanguageAllowed: true
#                  selectionCriteria:
#                    attributes:
#                      - type: ARTIST
#                        entityId: fake-artist-entity-id
      Environment:
        Variables:
          STR_PK_STR_SK_DYNAMODB_TABLE_NAME: !Ref StringPartitionKeyStringSortKeyTable
          STR_PK_NUM_SK_DYNAMODB_TABLE_NAME: !Ref StringPartitionKeyNumericSortKeyTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref StringPartitionKeyStringSortKeyTable
        - DynamoDBReadPolicy:
            TableName: !Ref StringPartitionKeyNumericSortKeyTable
        - SSMParameterReadPolicy:
            # Exclude leading forward-slash:
            ParameterName: alexa-private-music-skill/access-control/secret-key

  StringPartitionKeyStringSortKeyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-StringPartitionKeyStringSortKeyTable"
      BillingMode: PAY_PER_REQUEST
      TableClass: STANDARD_INFREQUENT_ACCESS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S

  StringPartitionKeyNumericSortKeyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-StringPartitionKeyNumericSortKeyTable"
      BillingMode: PAY_PER_REQUEST
      TableClass: STANDARD_INFREQUENT_ACCESS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: N
